export const App: React.FC = () => {
  return (
    <>
      <div>
        <div>
          <p>TODOを入力</p>
          <form>
            <input type="text" />
            <button>追加</button>
          </form>
        </div>
        <div>
          <p>未完了のTODOリスト</p>
          <ul>
            <li>
              <div>
                <p>未完了のTODO</p>
                <button>完了</button>
              </div>
            </li>
            <li>
              <div>
                <p>未完了のTODO</p>
                <button>完了</button>
              </div>
            </li>
          </ul>
        </div>
        <div>
          <p>完了したTODO</p>
          <ul>
            <li>
              <div>
                <p>完了したTODO</p>
                <button>戻す</button>
                <button>削除</button>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </>
  );
};
